### PR TITLE
Something seems off

### PR DESCRIPTION
**Pull request by crodeheaver**
@barberboy 
I'm fairly certain my stuff sorts properly. In the expected.txt it sorts it differently though. Mine sorts it from 1 to 25 then 26 to 50 in order. expected.txt sorts it in more of an ascii fashion with 1, 10, 11, etc. Is that how you want it?

### CODE REVIEW

**Comment by barberboy** [comment]
Haha, you are completely right. That's my bad.

**Comment by barberboy** [comment]
I've adjusted the test's expectations. Do you mind rebasing and pushing again?

This should work, but let me know if you run into any issues:

``` sh
git remote add upstream https://github.com/unioncollege-webtech/sorts
git fetch upstream
git rebase upstream/master
git push origin master --force
```

**Comment by crodeheaver** [comment]
Looks like it's working.

**Comment by barberboy** [comment]
Awesome—looks great, Colby.  :100:

**Pull request closed without merging**
